[package]
name = "nazrin"
version = "0.1.0"
authors = ["MelodyYuuka <melody@yunmengdu.cn>"]
edition = "2021"
description = "rust-participle"

[lib]
name = "nazrin"
crate-type = ["cdylib"]

[dependencies]
jieba-rs = "0.6.8"
pyo3 = { version = "0.21.1", features = ["extension-module"] }

[profile.release]
opt-level = 3
debug = false
# split-debuginfo = '...'  # 平台指定。
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false
